image: node:14
stages:
    - test
    - deploy

test-job:
    stage: test
    script:
        - echo "Running tests..."
        - npm install
        - CI=true npm test
        - echo "Tests finished%"
    only:
        - branches
          develop

deploy-job:
    stage: deploy
    script:
        - echo "Running tests..."
        - npm install
        - CI=true npm test
        - echo "Now deploy commands%"
    only:
        - branches
          master